// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdyrzxhsecirhnubfdqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkeXJ6eGhzZWNpcmhudWJmZHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzMwOTIsImV4cCI6MjA3MjA0OTA5Mn0.UiX85UIuZxoj1_UaE0ia7rgUcK9mlL4mgjn3sqZFiQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});